# Generated by Django 4.0.4 on 2022-09-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='products_Image',
            field=models.ImageField(upload_to='producting'),
        ),
    ]
