# Generated by Django 4.0.4 on 2022-09-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0002_alter_products_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='products_category',
            field=models.CharField(choices=[('Men', 'men'), ('Women', 'women'), ('Electronics', 'electronics')], default='men', max_length=50),
        ),
    ]
