# Generated by Django 4.0.4 on 2022-09-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0004_alter_products_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='products_name',
            field=models.CharField(max_length=50),
        ),
    ]
