# Generated by Django 4.0.4 on 2022-09-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0005_alter_products_products_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
