# Generated by Django 4.0.4 on 2022-09-20 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0008_alter_add_to_cart_pid_alter_add_to_cart_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_dateils',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommers.user'),
        ),
    ]
