# Generated by Django 4.0.4 on 2022-09-20 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0010_user_dateils_firts_name_user_dateils_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('coupon_code', models.IntegerField()),
                ('payment_request_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommers.products')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommers.user')),
            ],
        ),
    ]
