# Generated by Django 4.0.4 on 2022-09-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0011_purchace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_dateils',
            old_name='firts_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user_dateils',
            name='email',
            field=models.EmailField(default=0, max_length=50),
        ),
    ]
