# Generated by Django 4.0.4 on 2022-10-05 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0012_rename_firts_name_user_dateils_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='placed_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('coupon_amount', models.IntegerField()),
                ('payment_request_id', models.CharField(default=0, max_length=300)),
                ('payment_id', models.IntegerField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommers.products')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommers.user')),
            ],
        ),
        migrations.DeleteModel(
            name='purchace',
        ),
    ]
