# Generated by Django 4.0.4 on 2022-10-05 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0013_placed_order_delete_purchace'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommers.products')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommers.user')),
            ],
        ),
    ]
