# Generated by Django 4.0.4 on 2022-10-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0015_wishlist_item_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='placed_order',
            name='date',
            field=models.DateField(default=0),
        ),
    ]
