# Generated by Django 4.0.4 on 2022-10-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0018_alter_placed_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placed_order',
            name='date',
        ),
    ]
